# Generated by Django 4.1.7 on 2023-02-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=7)),
                ('salary', models.CharField(max_length=50)),
            ],
        ),
    ]
